### ISSUE TITLE
Scraper does not work

### ISSUE THREAD

**Issue by MarcelKlaczinski** [Patrick-Vogt/yellowscrape#2]
Hi, 
I tried to use your Scraper but unfortunately I only get 410 Error.
Do you have any idea?

Thank you in advance

**Comment by Patrick-Vogt** [comment]
Thank you!
Gelbeseiten changed the url structure. It works again :)

**Comment by MarcelKlaczinski** [comment]
Thank you :)

**Comment by MarcelKlaczinski** [comment]
I am new to Python, but unfortunately I get the following error:
![image](https://user-images.githubusercontent.com/31956106/61807646-3ad6c280-ae3a-11e9-91fd-5be0b74c3138.png)
